import { useState } from 'react'
import { connect } from "react-redux"
import { setInfo } from "../redux/actions/main"
import { getPageData } from 'pages/api/page'
import Head from 'next/head'
import Header from 'components/layout/header'
import styles from './Home.module.css'

const Home = (props) => {
  const { name, setInfo } = props
  const [ newName, setNewName ] = useState('');

  const changeHandler = (e) => {
    setNewName(e.target.value);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Test app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <h1>
          Here is a Homepage for Nextjs!!!
        </h1>
       <div className={styles.inputGroup}>
        <input className={styles.input}type="text" value={newName} onChange={changeHandler}></input>
        <button onClick={() => setInfo(newName)}>Test set info</button>
       </div>
        <h2>Redux works!!! {name}</h2>
      </main>
    </div>
  )
}

export const getStaticProps =  async (context) => {
  const { data } = await getPageData(['home']);

  if (!data || data.length === 0) {
      return {
          notFound: true
      }
  }

  return {
      props: {
          data: data[0],
          revalidate: 10
      }
  }
}

const mapStateToProps = state => {
  return { name: state.main.name }
 }
 
 const mapDispatchToProps = {
  setInfo
 }

 export default connect(mapStateToProps, mapDispatchToProps)(Home);


