import { getPageData } from 'pages/api/page'
import Head from 'next/head'
import Header from 'components/layout/header'
import styles from './Home.module.css'

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <h1>
          Here is a Homepage for Nextjs!!!
        </h1>
      </main>
    </div>
  )
}

export const getStaticProps =  async (context) => {
  const { data } = await getPageData(['home']);

  if (!data || data.length === 0) {
      return {
          notFound: true
      }
  }

  return {
      props: {
          data: data[0],
          revalidate: 10
      }
  }
}

